apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-frontend
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: frontend
          resources:
            requests:
              cpu: 150m
              memory: 192Mi
            limits:
              cpu: 400m
              memory: 384Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: backend
          resources:
            requests:
              cpu: 500m
              memory: 768Mi
            limits:
              cpu: 1500m
              memory: 1536Mi
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: todo-frontend-hpa
spec:
  minReplicas: 3
  maxReplicas: 6
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: todo-backend-hpa
spec:
  minReplicas: 3
  maxReplicas: 8
