apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: todo-app-staging
resources:
  - namespace.yaml
  - ../../base
patches:
  - path: patch-images.yaml
  - path: patch-capacity.yaml
  - path: patch-backup.yaml
