apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-postgres
  namespace: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-postgres
  template:
    metadata:
      labels:
        app: todo-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          env:
            - name: POSTGRES_DB
              value: todo
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: todo-secret
                  key: DATABASE_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: todo-secret
                  key: DATABASE_PASSWORD
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: todo-postgres-service
  namespace: todo-app
spec:
  selector:
    app: todo-postgres
  ports:
    - port: 5432
      targetPort: 5432
